### ISSUE TITLE
unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by sighil** [sighil/automacent#31]
unknown error: session deleted because of page crash and invalid session id must be handled as fatal exception and should break @Repeat loop

	Caused by: org.openqa.selenium.WebDriverException: unknown error: session deleted because of page crash
	from unknown error: cannot determine loading status
	from tab crashed
	(Session info: chrome=83.0.4103.97)
	Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
	System info: host: '27ffa98130b9', ip: '172.17.0.38', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-96-generic', java.version: '1.8.0_252'
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.97, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: /tmp/.com.google.Chrome.sWrAeD}, goog:chromeOptions: {debuggerAddress: localhost:38407}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
	Session ID: 72fe07f35f0b2a24b881d98f769c0715
	*** Element info: {Using=xpath, value=//vsc-left-panel//section[contains(@class,'tab-content active')]//li//span[contains(@class,'vcenter')]/parent::span[.='hs4-vc-ldu19.st.large']/ancestor::li[1]//li//span[contains(@class,'datacenter')]/..}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
		at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:353)
		at org.openqa.selenium.remote.RemoteWebDriver.findElementsByXPath(RemoteWebDriver.java:432)
		at org.openqa.selenium.By$ByXPath.findElements(By.java:348)
		at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:311)`

	Caused by: org.openqa.selenium.NoSuchSessionException: invalid session id
	Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
	System info: host: '27ffa98130b9', ip: '172.17.0.38', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-96-generic', java.version: '1.8.0_252'
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 83.0.4103.97, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: /tmp/.com.google.Chrome.sWrAeD}, goog:chromeOptions: {debuggerAddress: localhost:38407}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
	Session ID: 72fe07f35f0b2a24b881d98f769c0715
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
		at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
		at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
		at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
		at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
		at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandles(RemoteWebDriver.java:460)
		at com.automacent.fwk.core.BrowserControls.closeAllChildWindows_aroundBody8(BrowserControls.java:96)
		at com.automacent.fwk.core.BrowserControls$AjcClosure9.run(BrowserControls.java:1)
		at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
		at com.automacent.fwk.execution.StepAndActionCompiler.aroundStepCompilerAspect(StepAndActionCompiler.java:115)

**Comment by sighil** [comment]
https://github.com/sighil/automacent/commit/f5b27dabbca942019998a1e03cbc758e0e70ac20

**Comment by sighil** [comment]
Reopened to adjust the commit
